#!/bin/bash
check_dependency()
{
    CMD_X=$1
    echo -n "[?] checking dependency: $CMD_X ..."
    if ! [ -x "$(command -v $CMD_X)" ]
    then
        echo ""
        echo "[-] $CMD_X is not installed :(" >&2
        exit 1
    fi
    echo " [OK]"
}

# installer requirement checks
check_dependency 'curl'
check_dependency 'git'
check_dependency 'python'

# vim
echo "[-] remove previous installation ..."
sh uninstall

echo "[+] set up vim configure ..."
mkdir -p $HOME/.vim
path=$(pwd)

ln -s -f $path/vimrc $HOME/.vimrc
ln -s -f $path/vimrc-plugins $HOME/.vimrc-plugins

echo "[+] install vimplug ..."
curl -fLo $HOME/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

echo "[+] install vim plugins ..."
vim -u $HOME/.vimrc-plugins +PlugInstall +qall
